### ISSUE TITLE
Cannot insert NULL as value into table

### ISSUE THREAD

**Issue by debseal** [uber/vertica-python#136]
I am trying to insert NULL as value in a column based on a condition. The key is I only want it if a certain condition is true. Below is the code snippet:

    connection = vertica_python.connect(**self.vert_conn_info)
    cur = connection.cursor()
    insert_sql = """INSERT INTO {0}.{1} VALUES ('{2}', '{3}', {4})"""
    insert_sql_str = insert_sql.format(self.vert_schema_name,
        Config.VERT_TABLE_NAME_FOR_PLOT,
        self.run_date,
        exp_name,
        row.opu if not math.isnan(row.opu) else null
      )
    cur.execute(insert_sql_str) 
    cur.execute("commit;")

Error: 
NameError: global name 'null' is not defined

**Comment by Subzidion** [comment]
I'll give this a shot.

Python uses ```None``` instead of null, so when you say ```else null```, null will not be defined. If you were to use ```None``` I'm pretty sure it would it would embed the string "None" into the SQL statement instead of treating it as NULL which is what I think you want.

The code below should work. I took the single quotes out of the original SQL Statement and add them in the format string if it passes your test, otherwise it puts in NULL. Hope this fixes it!

```
insert_sql = """INSERT INTO {0}.{1} VALUES ('{2}', '{3}', {4});"""
insert_sql_str = insert_sql.format(self.vert_schema_name,
    Config.VERT_TABLE_NAME_FOR_PLOT,
    self.run_date,
    exp_name,
    "'" + str(row.opu) + "'" if not math.isnan(row.opu) else "NULL"
  )
```

**Comment by debseal** [comment]
@Subzidion : Yes, that does the trick. However, personally I feel that for such cases passing None from python side, should be then parsed as null for vertica by the library. As intuitively, they are kind of equivalent of each other. Just a thought. :)
