### ISSUE TITLE
Problem with nordic character i.e. ä

### ISSUE THREAD

**Issue by ruwen** [uber/vertica-python#34]
Got this error on this line in connection.py  self.connection.write(messages.Query(operation))

when execute('update users set lastname= :lastname where username = :username', {'lastname': 'someöö', 'username': 'sss'} 

Is it a encoding problem?

**Comment by jberka** [comment]
I'll see if I can sort this one out.

**Comment by jberka** [comment]
@ruwen Not sure if you're still dealing with this, but on the off chance you are, which version of the library this occur with? I can't reproduce it with the current version.

At the moment, non-ASCII characters seem to work fine with a Unicode query string. Using them as parameter values is broken due to an issue with psycopg2, which I'm still trying to find a workaround for.

**Comment by ruwen** [comment]
@jberka It's solved now. Solution is in 6a044c8718ed9ef34458735438fd7b354e286bb6

**Comment by jberka** [comment]
What are your locale settings? I changed the parameter substitution around a bit, and the psycopg2 adapt() and getquoted() functions are causing some issues with Unicode parameters now.
