### ISSUE TITLE
Connection VIA DSN?

### ISSUE THREAD

**Issue by Bennyelg** [uber/vertica-python#58]
connection = connect({
    'host': '127.0.0.1',
    'port': 5433,
    'user': 'some_user',
    'password': 'some_password',
    'database': 'a_database'

    })
any way to do it like pyodbc:
e.g.
vertica_python.connect('host=xxx.xxx.xxx;dsn=vertica;uid=vertica')
?

**Comment by jberka** [comment]
I don't think so (but I'm not totally familiar with ODBC, which is how this project came to exist in the first place). Because this library doesn't use ODBC at all (it's a Python implementation of the actual protocol, and doesn't require any ODBC libraries to be installed), we don't have any kind of ODBC config file that would support the format you're asking about.

**Comment by Bennyelg** [comment]
Thanks, I thought I'll be more easy to use if we specify less details although this connector is awesome already.

:)

**Comment by jberka** [comment]
@zer0n can you close this?

**Comment by zer0n** [comment]
@jberka done
