### ISSUE TITLE
"Cursor is closed" exception after upgrading to 0.4.5

### ISSUE THREAD

**Issue by sisoftrg** [uber/vertica-python#64]
After upgrading to 0.4.5 I'm got 'Cursor is closed' exception on second query. code example:
```
    sql = vertica_python.connect(params)

    cur = sql.cursor('dict')
    cur.execute("select 1 from dual")
    print(cur.fetchall())
    cur.close()

    cur = sql.cursor('dict')
    cur.execute("select 2 from dual")
    print(cur.fetchall())
    cur.close()
```

```
$ ./test.py 
[{'?column?': 1}]
Traceback (most recent call last):
  File "./test.py", line 23, in main
    cur.execute("select 2 from dual")
  File "/usr/local/lib/python2.6/dist-packages/vertica_python/vertica/cursor.py", line 47, in execute
    raise errors.Error('Cursor is closed')
vertica_python.errors.Error: Cursor is closed
```

this worked fine before and works with other sql databases.

**Comment by Bennyelg** [comment]
Check this case and you are right there is a problem.
probably something small in the cursor class I will check it

**Comment by vrbala** [comment]
connection.Connection uses cursor.Cursor as singleton created in constructor. And, after cursor.close() is called marking a cursor as closed, there is no reinitialization in next call to connection.cursor causing the error.

**Comment by Bennyelg** [comment]
Implement Singleton in python is a bad practice from the beginning.

**Comment by alexjikim** [comment]
i patched 0.4.6 to reopen the cursor on connection.cursor(). 

as things are implemented now, the connection/cursor objects are tightly coupled so we cant support multiple cursors per connection (the cursor is a property of connection). As such, "closing" a cursor would probably means one of two things: 1) closing the connection, 2) simply marking it as "closed", but nothing else.

I've gone forward with (2), because it seems silly to create a new cursor object or reboot the connection while this 1:1 connection/cursor relationship exists. Let me know if you guys disagree and what you think should be done instead.

**Comment by Bennyelg** [comment]
This is pretty clear.
Agree on that: Connection should hold only 1 cursor. 1:1 (connection/cursor) relationship is acceptable and very reasonable. multi cursor can cause issues. (on same connection)
Regarding the simply marking as a closed , mark as close will be clear, but an option to 're-open' it and not the connection itself could be good? think it's a minor fix.

**Comment by alexjikim** [comment]
0.4.6 will reopen the cursor (not create a new connection) if you call conn.cursor() again, so your script should work. Or did you mean have a way to explicitly reopen the cursor in the cursor object?

**Comment by Bennyelg** [comment]
When I open a connection it should be 1 connection. if i close it i will have to reopen it again.
But -> if I close cursor and want to use it again and the connection is still open, a simple  if check will do the trick and activate it again. a cursor close after each execute should be good practice do you think guys?

**Comment by Bennyelg** [comment]
@alexjikim  we understand each other .. ;] you did right on 0.4.6

**Comment by vrbala** [comment]
@alexjikim I understand that cursor.close exists merely to be compatible with python db api. Closing a cursor and opening it for use is pretty much a NO-OP. Maybe it is worth documenting? For anybody taking a first look, they expectation will be to have a separate cursor for every call to connection.cursor. 1:N connection to cursor doesn't add much value though. So it can be left alone after adding a note in README.

As an aside, reading through http://www.vertica-forums.com/viewtopic.php?t=723, ODBC and JDBC seem to error out when somebody calls an execute with a result set open rather than silently flushing the results (with 1:1 mapping from connection to cursor).  

Food for thought, maybe?!

**Comment by alexjikim** [comment]
hm good to know. will keep in mind for a future update.
