### ISSUE TITLE
cursor.rowcount is incorrect

### ISSUE THREAD

**Issue by eliangcs** [uber/vertica-python#77]
In vertica_python 0.3.6, it was ok:

```
In [4]: cursor.execute('SELECT 1 UNION SELECT 2')

In [5]: cursor.rowcount
Out[5]: 2
```

But in the latest 0.5.1, you have to iterate all rows to get rowcount:
```
In [10]: cursor.execute('SELECT 1 UNION SELECT 2')

In [11]: cursor.rowcount
Out[11]: 0

In [12]: cursor.fetchall()
Out[12]: [[1], [2]]

In [13]: cursor.rowcount
Out[13]: 2
```

**Comment by alexjikim** [comment]
in 0.3.6, vertica python read all rows into memory when execute() is called.
In 0.5.x, rows are streamed so the actual rowcount is unknown until all the data is read, which is why you are seeing this behavior.

I took another look at the messages that vertica returns, and i havent been able to find a way to determine rowcount without either reading all of the data, or doing some sort of select count(*). Ive updated the readme with information on how rowcount behaves in vertica_python.
