### ISSUE TITLE
executemany missing?

### ISSUE THREAD

**Issue by srinivasakp** [uber/vertica-python#79]
Hello,

I see that the module is missing executemany function, Do you have any plans to implement it in next version?

Regards,
Srinivasa KP

**Comment by alexjikim** [comment]
there are no current plans to implement executemany. whats your use case?

**Comment by 164747** [comment]
I have the same issue, I have a loop and generate a lot of objects. When I save them one-by-one, it takes ages. I suppose it would go faster if I could save them in one transaction.

**Comment by mverrilli** [comment]
@164747 If you are doing insert values, look at using `copy` instead.  For example, I funnel all my inserts to a queue and read X records off the queue (or after Y minute timer hit) and do a single copy. It's very fast.

**Comment by alexjikim** [comment]
yes, definitely use copy for writing many rows.
im closing this issue since its old, but feel free to reopen if theres a use case that executemany is required for.

**Comment by feinsteinben** [comment]
Hi,

I suggest to reopen this issue, for supporting pandas-vertica integration (pandas.to_sql method for uplaoding pandas dataframe to vertica table).

The executemany method is required to have this feature. I've implemented a poc version of executemany, and it indeed solves the pandas-vertica intergration. However, my implementation is not efficient, and uses many INSERT statements instead of COPY.

This integration works with this sqlalchemy-vertica dialect:
https://github.com/startappdev/sqlalchemy-vertica/tree/dev
and with this implementation of executemany:
https://github.com/uber/vertica-python/pull/142

**Comment by AndrewJudson** [comment]
I also think this should be reopened - it would be nice to support pandas. Otherwise people will have to go back to pyodbc

**Comment by vohnik** [comment]
Reopen it please, it is useful for updates too,  and pandas-vertica integration as was already mentioned.

**Comment by feinsteinben** [comment]
I think it was solved a long long time ago, in another PR.

**Comment by mverrilli** [comment]
Right, this one: #152
