### ISSUE TITLE
how to use application load balancing with vertica-python module

### ISSUE THREAD

**Issue by bhushanuparkar** [uber/vertica-python#84]
Could you please provide sample code to specify application load balancing as part opening connection with vertica python module. 

{code}
'ConnectionLoadBalance' : 1
{code}

**Comment by mnikhil-git** [comment]
to say how to provide backend options to startup message flow? I looked at http://www.postgresql.org/docs/9.2/static/protocol-message-formats.html StartupMessage documentation, it is unclear how the multiple options are to be passed followed by the terminator. It is also noted that the run time parameters could be set outside the startup message.

**Comment by alexjikim** [comment]
sorry, but im not sure i understand the ask here.

vertica-python doesn't do any load balancing. if you want to load balance queries across your vertica cluster, that would have to be handled outside of this module.

**Comment by mverrilli** [comment]
Vertica has native connection load balancing. When enabled, you can connect to any node and it will redirect you to another node.  In order to accomplish this, the driver must allow the redirect (connect to a different node). I don't know much about the protocol behind this.  vsql and jdbc both can do this (with an option enabled). This could possibly be an enhancement, (I don't personally use this, I just thought I'd add my 2 cents).

https://my.vertica.com/docs/7.2.x/HTML/index.htm#Authoring/AdministratorsGuide/LoadBalancing/AboutNativeConnectionLoadBalancing.htm

**Comment by uvu2112** [comment]
mverrilli makes a good point here. In order to use Vertica's [native connection load balancing](https://my.vertica.com/docs/9.0.x/HTML/index.htm#Authoring/AdministratorsGuide/LoadBalancing/AboutNativeConnectionLoadBalancing.htm) both the Vertica cluster and the client driver must enable load balancing.

With Vertica, you simply need to set the parameter: `SET_LOAD_BALANCE_POLICY('policy')`.

With the client you need to specify using load balancing.

VSQL Example:

```
vsql -U <user_name> -h localhost --enable-connection-load-balance
```

With ODBC you create the DSN with the `ConnectionLoadBalance` property:

```
[vertica_dsn]
Driver = /opt/vertica/opt/vertica/lib64/libverticaodbc.so
Database = db
Servername = localhost
ConnectionLoadBalance = true
UID = <username>
PWD = <password>
Port = 5433
```

This is a valid issue. It would be great to be able to specify `'connection_load_balance': True,` in the `conn_info` settings.
